locals {
  key_name           = "${var.aws_name_prefix}-vm"
  container_key_path = "${var.ssh_key_dir}/aws-vm.pem"
  host_key_path      = "ssh_keys/aws-vm.pem" # Relative to the host-side tofuenv directory.
  ssh_user           = "ubuntu"
}

# --- SSH key pair (generated by tofu) ---
resource "tls_private_key" "vm" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "vm" {
  key_name   = local.key_name
  public_key = tls_private_key.vm.public_key_openssh
}

resource "local_sensitive_file" "vm_key" {
  content         = tls_private_key.vm.private_key_pem
  filename        = local.container_key_path
  file_permission = "0600"
}

# --- Ubuntu 22.04 AMI ---
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

data "aws_vpc" "default" {
  default = true
}

# --- Security group (SSH) ---
resource "aws_security_group" "vm" {
  name        = "${var.aws_name_prefix}-vm-sg"
  description = "cm-centipede migration test VM"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.allowed_cidr]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Project   = "cm-centipede"
    ManagedBy = "opentofu"
  }
}

# --- EC2 instance used as the filesystem migration test target ---
resource "aws_instance" "vm" {
  ami                         = data.aws_ami.ubuntu.id
  instance_type               = var.aws_instance_type
  key_name                    = aws_key_pair.vm.key_name
  vpc_security_group_ids      = [aws_security_group.vm.id]
  associate_public_ip_address = true

  root_block_device {
    volume_size = var.aws_vm_volume_size
  }

  tags = {
    Name      = "${var.aws_name_prefix}-vm"
    Project   = "cm-centipede"
    ManagedBy = "opentofu"
    Purpose   = "migration-test"
  }
}
